// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaceuticaBack.Models;

public partial class Establecimiento
{
    public int IdEstablecimiento { get; set; }

    public string Nombre { get; set; }

    public string Calle { get; set; }

    public string Numero { get; set; }

    public int IdBarrio { get; set; }

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual ICollection<PersonalCargosEstablecimiento> PersonalCargosEstablecimientos { get; set; } = new List<PersonalCargosEstablecimiento>();

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();
}