// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FarmaceuticaBack.Models;

public partial class Pais
{
    public int IdPais { get; set; }

    public string NombrePais { get; set; }

    public virtual ICollection<Provincia> Provincia { get; set; } = new List<Provincia>();
}